- topic_name: "/world/world_demo/model/tugbot/link/scan_front/sensor/scan_front/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: "GZ_TO_ROS"
- topic_name: "/world/world_demo/model/tugbot/link/imu_link/sensor/imu/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: "GZ_TO_ROS"
- topic_name: "/world/world_demo/model/tugbot/link/camera_front/sensor/depth/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: "GZ_TO_ROS"
- topic_name: "/model/tugbot/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: "ROS_TO_GZ"